### ISSUE TITLE
What are the output files of the assembler?

### ISSUE THREAD

**Issue by conchoecia** [chanzuckerberg/shasta#1]
I would like to try your assembler but don't see any specification of what filetypes your assembler outputs in the documentation. Is it fasta or a graph?

**Comment by paoloczi** [comment]
Thank you for your interest. Here is an excerpt from the documentation under "Inspecting assembly results":

> Currently, the only output produced by the shasta software consists of various data structures stored in binary files in memory, visible as files in the data and Data directories. The most important such data structure is the global marker graph, as defined here. The shasta software implements http functionality that allows you to inspect these data structures using a Web browser. 

You may want to to take a look at the presentation which is part of the documentation, if you haven't already, for a description of the marker graph and some of the computational ideas being explored.

This code is at an early stage and does not yet perform global assembly, so it does not yet produce the output you would normally expect from an assembler (typically, FASTA files containing assembled contigs). It does perform local assembly in the http server: after the run is completed, you can start the http server (in memory or from disk) and, interactively from the browser, do a local assembly around a chosen marker of a read. This gives you the option to output assembled sequence in Fasta format, and also shows a marker alignment of supporting reads to assembled sequence. Keep in mind that this local assembly uses a simple minded algorithm based on a spanning tree, and there is certainly space for improvement there. You can also easily visualize the local marker graph used to perform this assembly, and perhaps contribute your own ideas and/or code to the process.

The http server also allows you to explore reads, compute a marker alignment of two reads, and explore the read graph that was used to create the marker graph. So I would encourage you to do a run, then start the http server and do some exploration.

Because of the lack of global assembly, it has not yet been possible to characterize the quality of assembly output. I hope to get to that in a reasonable amount of time, but there is some work to do first.

In term of performance, a human size assembly with 40X coverage runs in about 6 hours (up to construction of the marker graph, without global assembly) on a machine with 976 GB of memory and 32 cores (64 vCPUs, AWS instance type x1.16xlarge which typically costs around $2 per hour at spot prices).

**Comment by paoloczi** [comment]
I am closing this. Feel free to reopen if there are additional questions.

**Comment by paoloczi** [comment]
The code now creates assembly output in FASTA and GFA formats. They are both automatically created by RunAssembly.py. The test assembly for *E. coli* runs on a laptop in a few minutes and creates a single circular contig. The algorithm for local sequence assembly is at a very initial stage, so current output should be considered tentative.
