### ISSUE TITLE
Parameter suggestions for highly repetitive but homozygous plant genome

### ISSUE THREAD

**Issue by davidecarlson** [chanzuckerberg/shasta#217]
Dear Shasta team,

I'm currently trying to do an assembly using ~85 - 90x coverage ONT reads for a highly repetitive (probably 70-80% repeats) but homozygous plant genome that is roughly 1 Gb in size.  

The raw data were basecalled with Guppy 4.0 and the read N50 is 31k. Based on previous discussions regarding the tomato genome assembly, I used the following parameter  options:

```
--Align.maxSkip 50 \
--MinHash.m 3 \
--MinHash.minBucketSize 3 \
--MinHash.maxBucketSize 30 \
--MinHash.minHashIterationCount 30 \
--MinHash.minFrequency 3 \
```

The result (which was finished amazingly quickly!) was an 864 Mb assembly and a contig N50 of 837534. 

Given how quickly Shasta runs, I would like to try some additional parameter values to try to improve the results. 

Can you suggest any parameter values that I should consider using or other options to tweak?

Any suggestions would be most welcome!
Thanks!
Dave

**Comment by paoloczi** [comment]
I suggest using as a starting point configuration file `shasta/conf/Nanopore-Sep2020.conf`. You can use command line option `--config` to specify the configuration file. You can download the configuration file from GitHub, or get it from the tar file for the current release.

Let me know how that goes, and I can then make additional suggestions based on that. 

Keep in mind that if a parameter is specified both in the configuration file and on the command line, the latter takes precedence. This allows you to start with a configuration file and then override some of the parameters, keeping the rest as set in the configuration file.

**Comment by paoloczi** [comment]
For more information on Shasta configuration files, see [here](https://chanzuckerberg.github.io/shasta/CommandLineOptions.html#ConfigFile).

**Comment by davidecarlson** [comment]
Thanks!  I've tried rerunning the assembly using the Nanopore-Sep2020.conf both with and without the added parameters used in the Tomato assembly.  Here are the results:

Nanopore-Sep2020.conf  with no other changes:

Assembly size 277 Mb
N50 483969

Nanopore-Sep2020.conf + Tomato parameters:

Assembly size 608 Mb
N50 134264

So, neither of those assemblies performed as well as using the Tomato settings without the Nanopore-Sep2020.conf file.

**Comment by paoloczi** [comment]
Oh, now I remember - the tomato data required different assembly parameters that @bagashe attempted to optimize for, and you must be in a similar situation. If I remember, these reads were apparently less accurate than comparable reads for human genomes. I apologize for creating unnecessary extra work for you.

Not sure if @bagashe will see this because he is no longer working on Shasta, but let's see if we can improve on your results, starting with your first assembly which is the best so far. To do that, I need more information:

- Was that assembly "messy" or "fragmented" - that is, is the N50 limited mostly by branches in the assembly graph or by "dead ends" - segments than don't connect to anything. The easy way to find out is to load `Assembly.gfa` in [Bandage](https://rrwick.github.io/Bandage/) and look at it. Bandage is very easy to install and use, and you will find it generally useful if you are doing assembly work. Perhaps you could post here the picture you get when displaying the entire assembly graph in Bandage. The cure to improve assembly contiguity is heavily dependent on the answer to this question.

- Please post here the following files from the assembly: `AssemblySummary.html`, `LowHashBucketHistogram.csv`, `DisjointSetsHistogram.csv`. You can zip them or tar/gz, whatever is easier for you. These files should not be too large and will help me get an idea of what is going on in this assembly.

**Comment by davidecarlson** [comment]
Thanks for all the help!  I will take those steps and report back.
Best,
Dave

**Comment by davidecarlson** [comment]
I'm attaching a tar.gz file that includes the `AssemblySummary.html`, `LowHashBucketHistogram.csv`, and `DisjointSetsHistogram.csv` files. 

In addition, I've attached a picture of the assembly graph from Bandage. 

Please let me know if I can provide any more information.
Thanks again!
Dave

![graph](https://user-images.githubusercontent.com/25590156/102627587-6684d780-4116-11eb-91b0-d86a53a2dddc.png)

[shasta_files.tar.gz](https://github.com/chanzuckerberg/shasta/files/5716320/shasta_files.tar.gz)

**Comment by paoloczi** [comment]
I see some symptoms that perhaps these reads somehow may originate from a population of individuals with different genomes, rather than for a single individual. I know that for a plant the word "individual" may be ill defined, so I will rephrase as wondering if the reads originate from a population of cells with different genomes, rather than from a set of cells all with identical genomes. Is it possible that we are in the "population" situation? If so, Shasta is not well equipped to deal with it, although there are some things that we could try in that case.

If you can rule out the "population" situation I will try and propose a new set of assembly parameters to try, or even try some experimentation myself after the holidays if you are willing to share the data privately.

**Comment by davidecarlson** [comment]
I believe we can rule out the "population" situation. The data come from a plant that is outcrossing in the wild but the tissue used in sequencing was from a single individual that was the product of inbreeding in the lab, so there should not be genomes from multiple cells, and the genome itself should be (relatively) homozygous.

I would be happy to try any assembly parameters you can suggest.  I can also talk to my PI and collaborators about sharing the data privately, though I'd prefer to keep working on it myself to the extant possible.
Thanks!
Dave

**Comment by paoloczi** [comment]
I suggest that you use a Shasta assembly with reduced bubble removal to test for the presence of multiple populations. The following options would do the job:
```
--config Nanopore-Sep2020.conf --MarkerGraph.simplifyMaxLength 10
``` 
That will cause only very small bubbles to be removed. Sometimes systematic errors in sequencing can generate small bubbles.

Then use Bandage to look at `Assembly.gfa` or, better, `Assembly-BothStrands.gfa` with "Arrowheads in single node style" turned on in Bandage `Tools/Settings`. If the population is truly homogeneous, there should be almost no bubbles. Bubbles will destroy contiguity, so this assembly will not give a good N50 - it is for experimentation only.

For this kind of investigation it may also be useful to start using the Shasta http server to investigate assembly results. That requires running the assembly with options that cause it to store binary data for further use. There is some information on that [here](https://chanzuckerberg.github.io/shasta/InspectingResults.html) but I can answer questions.

If this confirms that the cell population being sequenced is truly homogeneous I will make additional suggestions. I am perfectly happy to cooperate in this mode of operation, but you must be prepared to the possibility that it may take a few iterations to converge to a satisfactory assembly.

**Comment by paoloczi** [comment]
To rule out the presence of multiple populations, it may also be useful to do a k-mer analysis. I know that there are tools to do that, but unfortunately I am not familiar with them and so I am not able to point you in the right direction.

**Comment by davidecarlson** [comment]
Thanks, I'll take those steps and report back. 

I confirmed with my PI that the sample was taken from a single individual that has been stably inbred for many generations. That said, I suppose contamination is a possibility.

I have some Illumina data for this same sample which I can analyze with the Kmer Analysis Toolkit. I believe KAT can be used to look for contamination. 

I certainly don't mind go through multiple iterations.  I really appreciate your help. I'll let you know once I have more results.
Best,
Dave

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion, but feel free to reopen it or create a new one if additional discussion topics emerge.
