### ISSUE TITLE
Difficulty to assemble a tandem duplication

### ISSUE THREAD

**Issue by CTriay** [chanzuckerberg/shasta#227]
Hello,

I'm trying to assemble MinION Long reads of 2 haplotypes differing only from a tandem duplication.
I know I have long reads crossing the tandem duplication (because they do map on my "theoretical duplicated haplotype"), and there is a mean coverage of 6x along this region. I know the coverage are super low, but the reads overlap well along this region and the duplicated genes carry indels of ~200 to 400 bp specific to one haplotype at several loci.
However, I cannot manage to assemble this region using Shasta. The final Assembly is a hybrid of the two haplotypes.
My guess is that this duplication might be seen as a "bubble" along the steps, and thus, be removed for the final graph.

I changed the following parameters `--MarkerGraph.minCoverage=2` in order to keep the 2 haplotypes even though the coverage of each haplotype is low. Unfortunately, it leads to the building of only 1 contig which is a hybrid of my 2 expected haplotypes.

What parameters should I play with to better reconstruct the 2 distinct haplotypes in 2 different contigs in the final assembly?

Thanks for your help,

Best, 

Cécile

PS: I'm new to "graphs" assemblies, so I might not understand everything correctly, but I did a schematic representation of what I think might occur in this region.
[Schema_tandem_dupli_graph.pdf](https://github.com/chanzuckerberg/shasta/files/5850951/Schema_tandem_dupli_graph.pdf)

**Comment by paoloczi** [comment]
Shasta default parameters are not necessarily optimal for any application, and for that reason we provide In directory `shasta/conf` sample configuration files that work well under specific conditions. We currently recommend `shasta/conf/Nanopore-Sep2020.conf` for most nanopore applications, but those settings are specific to the Guppy base caller version 3.6.0 or newer, PromethIon data, and coverage at least 20x. It does not apply in your situation, which is a very hard one as you have old reads, very low coverage, and duplications of sequence.

Given the data available to you, it will be hard to separate the two haplotypes by any means. In any event, you may want to try completely turning off bubble removal via the following command line option:

```
 --MarkerGraph.simplifyMaxLength ""
```

(the two quote characters are required). You may end up with lots of bubbles, many of them erroneous. You could also try the following to remove only the smaller bubbles:

```
 --MarkerGraph.simplifyMaxLength 5
```
This will remove bubbles smaller than 5 markers, which with typical assembly parameters corresponds to about 70 bases. The bubbles you are looking for are 200 bases or longer, so they would not be removed.

I will be happy to help more, so feel free to report what happens when you try the above.

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion, but feel free to reopen it or create a new one if additional discussion topics emerge.
