### ISSUE TITLE
No recipe on bioconda for 0.7.0

### ISSUE THREAD

**Issue by hoelzer** [chanzuckerberg/shasta#257]
Is it planned to add also a bioconda recipe for the latest release? 

Thanks!

**Comment by paoloczi** [comment]
I have mixed feelings about this, because Shasta could be packaged in many different ways, and I hesitate to add support for all possible packaging solutions, as that could become hard to maintain. My preference would be for changes that are  specific to a packaging solution to be made outside the Shasta repository, but I could be convinced to the contrary if strong arguments for doing it in the Shasta repository itself emerge.

In addition, most of Shasta functionality is provided by a single static executable with no external dependencies, so the added value of packaging is minimal. However I do understand the convenience of having Shasta become part of a popular packaging solution - `bioconda` in this case.

Perhaps you or somebody else could create a `shasta-bioconda` repository that implements your desired recipe?

**Comment by hoelzer** [comment]
Hi! Thanks for the fast reply! Actually, I also just figured out how easy
the install is bc/ Shasta comes with all dependencies in a single
executable - great work!

I think conda is just a really default way of installing tools for the
community and so the first thing users are looking for. Afaik, you can also
automate this and every time a new Shasta release appears a new recipe is
build. Unfortunately, I can not provide this bc/ my exp here is also
limited.

And also for me the issue is basically solved bc/ the available executable
works ;)

**Comment by paoloczi** [comment]
Cool. Let's leave this issue open for a bit, and give a chance to others to pitch in.

**Comment by paoloczi** [comment]
Given that there were no additional comments, I will close this.
