### ISSUE TITLE
Extremely low CPU utilization

### ISSUE THREAD

**Issue by kautto** [chanzuckerberg/shasta#33]
Dear shasta maintainers,

I have shasta (binary release, didn't compile it) running on an AWS instance on ONT data. Although the server has 96 cores, the CPU utilization is extremely low - I mean it hovers for LONG periods of time at 0%, occasionally using 1-10%, and I've seen it go up to 100% once. The memory usage is pretty high (hundreds of gigs), but the CPU's just aren't doing anything. I didn't see any specific parameters to pass to tell it to run multi-threaded. Any ideas?

**Comment by paoloczi** [comment]
If you are not already, make sure to use the command line options suggested [here](https://chanzuckerberg.github.io/shasta/Performance.html) to optimize assembly performance:

`--memoryMode filesystem --memoryBacking 2M`

These options require root privilege via `sudo`, but you should not have any problems with that on an AWS instance.

Also, see [here](https://chanzuckerberg.github.io/shasta/Running.html#MemoryModes) for additional background information on these options and [here](https://chanzuckerberg.github.io/shasta/Running.html#MemoryRequirements) for a discussion of memory requirements.

If you still have the problem when using those options, please comment again and provide the following information:
* Amount of memory (RAM) on the machine you are using and/or AWS instance type.
* The Linux distribution and version you are using, and/or the AWS AMI.
* Log output (stdout) for the partial run, up to the point where the stall begins.
* The estimated size of the genome you are assembling and/or species.
* The total size of the input Fasta files.

We have been routinely assembling human genomes from ONT reads at coverage around 60x in about 6 hours on `x1.32xlarge` AWS instances and I am confident you will be able to achieve similar results.

**Comment by paoloczi** [comment]
I forgot to mention in the previous comment that the number of threads is adjusted automatically to use all of the machine virtual processors during parallel phases. You don't need to specify an option for that.

However, the code does have some sequential phases which typically take about 30% of total assembly time for a healthy assembly.

**Comment by kautto** [comment]
We are currently using r5.24xlarge instances running CentOS 7. They have 96 cores and 768 gigs of RAM. I'm running it human data (~3Gb genome), the FASTA is about 108 gigabytes.

It's slowly moving along the steps:
```
2019-Jun-10 18:13:24.664944 LowHash iteration 0 begins.
Alignment candidates after iteration 0: high frequency 6906035, total 34683644, capacity 34683644.
2019-Jun-10 21:57:56.094692 LowHash iteration 1 begins.
Alignment candidates after iteration 1: high frequency 14744095, total 59113086, capacity 73710940.
2019-Jun-10 22:49:48.368473 LowHash iteration 2 begins.
Alignment candidates after iteration 2: high frequency 20966454, total 79748219, capacity 105472505.
2019-Jun-10 22:59:44.574677 LowHash iteration 3 begins.
Alignment candidates after iteration 3: high frequency 26103243, total 98477972, capacity 130879900.
2019-Jun-11 04:19:29.504740 LowHash iteration 4 begins.
```

We just added in the option to run X1 instances this morning, but since we're running everything through our SGE grid, I can't run sudo. The institute's information security policy strongly restricts the use of any sudo/root access, even on these AWS instances. Is there a way to utilize the 2M pagefiles without sudo access? One of our senior techs said they can have the instance load hugetlbfs by default, but if the binary tries to run sudo, it'll still fail.

**Comment by paoloczi** [comment]
Shasta is not designed to be used in a cluster but on a large dedicated machine, and therefore SGE is not the right tool for you. You are much better off starting the instance yourself. This way, you only keep the instance up for the minimum amount of time necessary for your run instead of having to configure it in your SGE cluster. This will save money for your organization. In addition, you can get root access to your instance without fear of disturbing other users. With the recommended options, your assembly should run in 4-6 hours on an `x1.32xlarge` instance, and may even run on an `x1.16xlarge` instance. Given the output you sent, there is no point attempting to run it, even on an `x1` instance, without using the recommended options.

You are trying to perform a significant computation, and you should be able to make the point with your institution that SGE is not an adequate solution for your needs. It is a 20+ year old tool, designed for a now virtually defunct platform, that lends itself to computational paradigms valid in the 1990s but now becoming obsolete. Much of the functionality of SGE, for example, is provided in much more flexible ways by current cloud computing platforms.

It is in theory possible to configure the `hugetlbfs` filesystem once, then run Shasta without root access, but this is not easily supported by existing code, would be complex from an administrative point of view, and would still not lend itself well to use under SGE. Another possibility would be to just get limited `sudo` access to a small number of commands, but given the SGE setting it is unlikely that you will be able to get that.

If your IT organization is not sensitive to your needs, it would be very easy for you to set up an AWS account and pay for it using your group's funding. That way you would have full control over your computational resources.

**Comment by paoloczi** [comment]
Actually, I take back my comment that it is not worth trying `x1` instances in your SGE setting. If your SGE instances are configured with swap space (not commonly done in modern times and with large memory machines), it is possible that your slow run was swapping due to insufficient memory, and if that is the case working on a `x1.16xlarge` or, better, `x1.32xlarge`, instance may work - even though it will certainly not deliver full performance.

If you see another slow run, please note swap usage. If there is swap usage, you certainly need more memory as Shasta is designed to run with all data structures in memory.

**Comment by kautto** [comment]
Hi @paoloczi,

unfortunately, the SGE usage and other institutional policies are decided high above my pay grade and I have no say in the matter. For jobs like this, I request the entire node at a time, so there aren't issues with competing processes running on them. From what aspect, it should be the same as if I had the instance separately spun up. Even if I requested a separate AWS instance, they would require the same security policies to be enforced, so I don't think I can get around the sudo issue. 

I'll give the X1 instance a shot to see how it performs. Interestingly, it doesn't look like there's any swap usage even on the current instance:
```
              total        used        free      shared  buff/cache   available
Mem:      783896508   139963876   300438004   117786748   343494628   523339796
Swap:             0           0           0
```

But some of the iterations are still taking quite long. Not sure why there's the discrepancy (i.e. 10 mins vs 3 hours vs 8 hours)
```
2019-Jun-10 18:13:24.664944 LowHash iteration 0 begins.
Alignment candidates after iteration 0: high frequency 6906035, total 34683644, capacity 34683644.
2019-Jun-10 21:57:56.094692 LowHash iteration 1 begins.
Alignment candidates after iteration 1: high frequency 14744095, total 59113086, capacity 73710940.
2019-Jun-10 22:49:48.368473 LowHash iteration 2 begins.
Alignment candidates after iteration 2: high frequency 20966454, total 79748219, capacity 105472505.
2019-Jun-10 22:59:44.574677 LowHash iteration 3 begins.
Alignment candidates after iteration 3: high frequency 26103243, total 98477972, capacity 130879900.
2019-Jun-11 04:19:29.504740 LowHash iteration 4 begins.
Alignment candidates after iteration 4: high frequency 30612727, total 115959419, capacity 156131707.
2019-Jun-11 16:54:07.542755 LowHash iteration 5 begins.
Alignment candidates after iteration 5: high frequency 34775203, total 132542276, capacity 179991085.
2019-Jun-12 01:22:59.913047 LowHash iteration 6 begins.
```

**Comment by paoloczi** [comment]
Normally one of these iterations should take under one minute for a run like you are attempting, so something is still severely wrong. 

I see that the total memory reported is 783896508. This is not consistent with an x1 instance. Can you check on that?

It is unlikely, but possible, that your data contain something unusual which causes the run to go so slowly. Because of that, I will be happy to do this one run for you, if you point me to the input data. If the run is still slow for me I will use it for debugging. Either way, I will give you assembly output when the run completes, and I will destroy all of the files when done.

**Comment by kautto** [comment]
Sorry, those stats weren't for the x1, it's for the r5. I have the x1 instance starting up right now. I'll let you know how that looks once it starts running.

The data is just publicly available NA12878 data from the Nanopore WGS consortium (https://github.com/nanopore-wgs-consortium/NA12878) that I'm using for testing purposes. Only difference is that I ran it through the new high-accuracy guppy model.

I'll let you know how x1 looks once it starts up.

**Comment by paoloczi** [comment]
Let's see how the run on the x1 instance does, and if that is still slow you can point me to the exact input that you are using. I did some experimentation with that data set some time ago and I had no unusual issues.

**Comment by kautto** [comment]
It's running significantly faster - iteration steps that took hours on the r5 instance completed in minutes on x1. So something else in the environment must have been the bottleneck. 

Do you have a ballpark estimate of how much better the performance is with 2M pages?

**Comment by paoloczi** [comment]
I only tested this once on a human assembly. That one time, on a `x1.32xlarge` instance, the assembly with `--memoryMode filesystem --memoryBacking 2M` ran about 30% faster compared to using default options (5-6 hours versus 7-9 hours approximately, if I remember correctly).

**Comment by paoloczi** [comment]
I heard from another user that she saw a slow down of only 10-20% when running with the default options on an `x1.32xlarge` AWS instance. This should be good news for you.

**Comment by kautto** [comment]
It actually completed exceptionally fast on the x1.32xlarge instance - 2.78 hours wall time for the entire thing. The job that I have running on the r5.24xlarge instance is still stuck on iteration 6, and it's been working on the assembly for about 3 days now. Just for curiosity's sake, I'm letting it run a bit longer, but it seems like something in the environment (possibly the mounted network storage) is acting as a really bad bottleneck.

My takeaway from this is that even if most of the processing is supposed to happen in memory, having slow storage seems to really kill the computational efficiency.

**Comment by paoloczi** [comment]
Great that you are able to get good performance even with the default options.

However, I don't buy your explanation of the slow speed on the r5 instance, because Shasta does almost no I/O during the assembly and therefore assembly performance should not be affected by storage or network performance. The only I/O Shasta does is for reading the input reads, writing the assembly output files, and writing a small number of text files containing summary information for the run.

There must be something else going on on the r5 instance. Perhaps your system administrator can run some monitoring tools to figure out what the machine is doing. The assembly will take months to finish at this rate. But it's great that you can now run a de novo assembly for a human genome in under 3 hours.

**Comment by kautto** [comment]
You're right, something made the whole instance become unresponsive. top didn't show any actual activity, but the sysadmin couldn't even get a full process list to show up. Had to kill the session. Maybe it was just a fluke.

I plan to try it again on an r5 instances just to see if I can get it to run. Might be that we'll just have to use dedicated x1 instances for it.

**Comment by paoloczi** [comment]
For human assemblies we have been using `x1.32xlarge` instances. At $13/hour, if your assembly takes under 3 hours it's $40 per assembly, a very reasonable cost, and much less than sequencing costs. And you can reduce it by about a factor of 3 if you use spot instances, although your SGE setup will probably not allow you to do that.

`x1.16xlarge` may also be ok for human assemblies with low coverage, but I am afraid going to `r5` instances is probably pushing your luck. And the 768 GB `r5` instance has about the same cost as the 976 GB `x1.16xlarge` (but it's true you get fewer processors).

`x1.32xlarge` will be the safest and fastest way to go in most cases, for human assemblies. With this instance type, a human assembly seems to usually take a number of hours equal to coverage divided by 10 (6 hours at coverage 60x).

Hopefully your SGE setup will allow you to start your instance only when a job runs and shut it down when done, otherwise things could get pretty expensive if you are forced to keep the instance up all the time.

**Comment by paoloczi** [comment]
So, to summarize this, the issue was due to either insufficient memory or unresolved system issues on the machine you were initially using. When you ran on an `x1.32xlarge` instance you were able to run the assembly with good performance (under 3 hours for a human assembly) even without using the Shasta options recommended for best performance.

I am closing this because there were no comments in a few days, but feel free to reopen if necessary. If new performance issues arise, please create a new issue.
