### ISSUE TITLE
unable to build from source

### ISSUE THREAD

**Issue by sachet-mittal** [chanzuckerberg/shasta#34]
Hi,
I am not sure if this is a bug or me just stupid. I also couldn't find documentation for building from source.

Steps performed:
1) Download the code from git
2) mkdir build
3) cd build
4) cmake ..
5) make 

Expected result:
Build should complete successfully

Actual Result:
Fails with error:
[  0%] Building CXX object src/CMakeFiles/shasta.dir/AlignmentGraph.cpp.o
[  1%] Building CXX object src/CMakeFiles/shasta.dir/AssembledSegment.cpp.o
[  2%] Building CXX object src/CMakeFiles/shasta.dir/Assembler.cpp.o
In file included from /soe/smittal2/shasta/source/src/Assembler.cpp:1:0:
<hidden_folder_path>/src/Assembler.hpp:24:10: fatal error: marginPhase/callConsensus.h: No such file or directory
 #include "marginPhase/callConsensus.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by AlBaarS** [comment]
I had the same problem. Couldn't solve it unfortunately, but if you're in a hurry, here's a workaround; You can use the executable just fine and copy it to other directories; it will still work.
Also responding to get notified when a solution is posted.

**Comment by paoloczi** [comment]
The documentation provides a [section](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html]) that explains in detail how to build from source. Please read that entire page (it will take only about one minute) and follow the directions there. Keep in mind that, as explained there, building from source is only supported for Ubuntu 16.04 and Ubuntu 18.04, and that the script that install prerequisites requires root privilege via sudo.

If you still cannot build after reading the documentation, please comment again. Otherwise, please close the issue.

Also, keep in mind that in many cases you don't need to build from source and instead you can just download the executable or the entire build from the [GitHub page for Release 0.1.0](https://github.com/chanzuckerberg/shasta/releases/tag/0.1.0).

**Comment by sachet-mittal** [comment]
Thanks. I somehow missed that tab on the page.

I have some other issues, will raise issues for them after some more debugging.
