### ISSUE TITLE
Unfair comparisons in the 'shasta' paper ?

### ISSUE THREAD

**Issue by bitcometz** [chanzuckerberg/shasta#44]
Hello,
in your paper "Efficient de novo assembly of eleven human genomes
using PromethION sequencing and a novel nanopore
toolkit",
you mension the Canu assembly of CHM13 is 85.8M and compare this results to those generated by other tools with only ONT reads.

It is unfari, since the 85.8m assembly is generated with many other approaches:

"The current assembly draft (v0.6) is generated with **Canu v1.7.1** including rel1 data up to 2018/11/15 and incorporating the previously **released PacBio data**. Two gaps on the X plus the centromere were **manually resolved**. Contigs with low coverage support were split and the assembly was **scaffolded with BioNano**. The assembly was polished with two rounds of nanopolish and two rounds of arrow. The X polishing was done using unique markers matched between the assembly and the raw read data, the rest of the genome used traditional polishing. Finally, the assembly was polished with **10X Genomics data**. We validated the assembly using independent BACs. The overall QV is Q37 (Q42 in unique regions) and the assembly resolves over 80% of the bacs (280/341).

The assembly is 2.94 Gbp in size with 503 scaffolds (593 contigs) and an NG50 of 83 Mbp (70 Mbp)"

https://github.com/nanopore-wgs-consortium/CHM13

Best

**Comment by paoloczi** [comment]
I am not sufficiently knowledgeable about the CHM13 analysis, but I will invite the
[paper](https://www.biorxiv.org/content/10.1101/715722v1) coauthors to comment here.

**Comment by skoren** [comment]
As far as I'm aware the assembly being evaluated in that section is not v0.6 but the rel2 assembly from the CHM13 consortium from Canu, without any polishing or post-processing. You can see this from the BAC analysis in the supplement of the paper (https://www.biorxiv.org/content/10.1101/715722v1.supplementary-material, supplementary tables 6/7). The identity of the BACs for the Canu assembly is only Q21, not Q37 as for the v0.6 assembly. Further, here are the stats for the rel2 asm with a genome size of 2.8g:
```
Total units: 559
BasesInFasta: 2919693163
Min: 2,315
Max: 166,625,045
N25: 104,817,486 COUNT: 6
N50: 85,169,819 COUNT: 13
N75: 45,101,454 COUNT: 25
```

The v0.6 assembly is only used to set a ground-truth for base-level identity for assembly quality evaluation, which makes sense since it's the most correct representation of CHM13 we have.

**Comment by kishwarshafin** [comment]
Hello, @skoren's comment is right. For the polisher section of the paper, we used all unpolished assemblies. I think a clear statement in the description of the figure would clear the confusion. In our next revision, we will take this issue into consideration and fix it. Thanks for bringing this in our attention.

**Comment by paoloczi** [comment]
Because there are no additional comments I am closing this issue. Feel free to reopen it if additional discussion is warranted.
