### ISSUE TITLE
'Resource temporarily unavailable'

### ISSUE THREAD

**Issue by SchwarzEM** [chanzuckerberg/shasta#57]
I am running what should be a perfectly reasonable shasta run (assembling long reads of a 320-Mb genome at 100x coverage) on a major computer cluster (NSF XSEDE Bridges).  Everything went apparently fine until, with no warning, the assembly died with this error message:

`2019-Sep-16 20:16:17.364582 Terminated after catching a runtime error exception:`
`Resource temporarily unavailable`

Is there some obvious reason why I should have gotten this error?  And, if so, what am I supposed to do about it?  (I cannot have sudo status on a massively shared cluster.)

**Comment by paoloczi** [comment]
I will have to research this a bit. To help me out, can you send the last few lines of the log output plus a description of the machine configuration, the command line options used, the amount of input coverage, and the expected genome size?

**Comment by paoloczi** [comment]
Also please let me know which Shasta release you are using, or if you built the code yourself at what commit (use `git log -1` to get that).

**Comment by paoloczi** [comment]
You may have hit a limit on the maximum number of threads allowed. It is possible that your cluster, being designed for shared usage, enforces a maximum number of threads per process. Linux provides various ways to enforce such a limit. You could ask your cluster administrators about that.

If this is the case, you can use Shasta option `--threads` to specify the number of compute threads (the total number of threads will equal the number you specify plus one). However this will slow you down. By default, Shasta uses a value equal to the number of virtual processors (typically equal to twice the number of cores).

I will improve the error message that gets written out if Shasta fails to start enough threads.

Shasta is designed for use on a dedicated, rather than shared, machine with sufficient memory to run the assembly entirely in memory. If such an environment is not available for you, you can rent it by the hour at very reasonable prices from the major cloud computing platforms. This would also have the advantage of giving you root access to the machine, and therefore the ability to run with the more efficient options `--memoryMode filesystem --memoryBacking 2M`.

I still encourage you to give me the information I requested above, as this is only a tentative diagnosis.

**Comment by paoloczi** [comment]
Since no additional information has emerged, I will close this issue for now. Feel free to reopen it if more information becomes available. I added a better error message when failure to start a thread occurs.

**Comment by SchwarzEM** [comment]
Thanks, @paoloczi -- I had meant to get back to you, but have not had time.  Also, it sounds as if the real problem is that I should run this assembler on the cloud (where I can have root/superuser status) rather than try to run it on the NSF XSEDE Bridges cluster (where I absolutely can't).
